---
title: "sibei"
author: "Sibei Liu sl4660"
date: "2020/3/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyselect)
require(survival)
require(quantreg)
require(glmnet)
require(MASS)
require(pROC)

data_all=read_csv("./breast-cancer.csv")
data=data_all[,2:12] %>% mutate(
  diagnosis=factor(diagnosis, levels = c("B","M"), labels = c(0,1))
)

# standardize
data2=scale(data[,2:11])
data2=cbind(data[,1],data2)



cancer = read_csv("breast-cancer.csv") %>% 
  mutate(diagnosis = as.numeric(factor(diagnosis, levels = c("B","M"), labels = c(0,1)))-1) %>% 
  mutate(radius_mean = scale(radius_mean))

cancer_scale = scale(cancer[3:12])
class(cancer_scale)
cancer_matrix = cbind(rep(1,569),cancer_scale)
cancer_matrix[,2]
## standardize data!!

```

```{r}
linear=glm(diagnosis~.,family=binomial(link='logit'),data=data2)
summary(linear)
lambda_max=max(coef(linear))
lambdas=seq(lambda_max,0,by=-2)
```

```{r}
S=function(solution,lambda){
  i=1
  for(i in 1:length(solution)){
  if (asb(solution[i])>lambda){
    if(solution[i]<0){
      return(solution[i]+lambda)
    }else{return(solution[i]-lambda)}
  }
  else{return(0)}
}}
```


I hate matrix


cancer_logit = cancer[,3:12] %>% cbind(cancer[,2])

# quadratic approximation
quadratic_appro = function(data, beta_vec){
  x = cancer_matrix
  y = as.matrix(data$diagnosis)
  pi=exp(x%*%beta_vec)/(1+exp(x%*%beta_vec))
  wi=pi*(1-pi)
  zi=x%*%beta_vec+(y-pi)/wi
  
}




